title: <p align="center"> Divya Srinivasan </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/Divya3006">GitHub</a>
  
  <br>   
  I am a Senior Developer at SAP Labs. I have joined IIIT-B ML/AI course.
  <br>
  </p>



theme: jekyll-theme-minimal
